---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-redis-lucassilva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverless-redis-lucassilva
  template:
    metadata:
      labels:
        app: serverless-redis-lucassilva
    spec:
      containers:
      - name: serverless-redis-lucassilva
        image: lucasgabrios/serverless:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/opt/usermodule.py"
          subPath: pyfile
        env:
        - name: REDIS_HOST
          value: "192.168.121.48"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: lucascarvalho
              key: REDIS_OUTPUT_KEY
        - name: REDIS_MONITORING_PERIOD_SECONDS
          valueFrom:
            configMapKeyRef:
              name: lucascarvalho
              key: REDIS_MONITORING_PERIOD_SECONDS
        - name: USER_CODE_BASE64
          valueFrom:
            configMapKeyRef:
              name: lucascarvalho
              key: USER_CODE_BASE64
        - name: USER_ENTRYPOINT_FUNCTION
          valueFrom:
            configMapKeyRef:
              name: lucascarvalho
              key: USER_ENTRYPOINT_FUNCTION
      volumes:
      - name: pyfile
        configMap:
          name: pyfile
          